/** i18n labels for PDF generation — English, Russian, Kazakh */

export type Lang = 'en' | 'ru' | 'kk';

export interface Labels {
  summary: string;
  keyPoints: string;
  tasks: string;
  tags: string;
  transcript: string;
  taskCol: string;
  priorityCol: string;
  statusCol: string;
  pending: string;
  done: string;
  high: string;
  medium: string;
  low: string;
  noTasks: string;
  footer: string;
}

export const i18n: Record<Lang, Labels> = {
  en: {
    summary: 'SUMMARY',
    keyPoints: 'KEY POINTS',
    tasks: 'TASKS',
    tags: 'TAGS',
    transcript: 'FULL TRANSCRIPT',
    taskCol: 'Task',
    priorityCol: 'Priority',
    statusCol: 'Status',
    pending: 'Pending',
    done: 'Done',
    high: 'HIGH',
    medium: 'MED',
    low: 'LOW',
    noTasks: 'No actionable tasks found.',
    footer: 'Generated by Voice Bot',
  },
  ru: {
    summary: 'КРАТКОЕ СОДЕРЖАНИЕ',
    keyPoints: 'КЛЮЧЕВЫЕ МОМЕНТЫ',
    tasks: 'ЗАДАЧИ',
    tags: 'ТЕГИ',
    transcript: 'ПОЛНАЯ ТРАНСКРИПЦИЯ',
    taskCol: 'Задача',
    priorityCol: 'Приоритет',
    statusCol: 'Статус',
    pending: 'В ожидании',
    done: 'Готово',
    high: 'ВЫСОКИЙ',
    medium: 'СРЕДНИЙ',
    low: 'НИЗКИЙ',
    noTasks: 'Задачи не обнаружены.',
    footer: 'Создано голосовым ботом',
  },
  kk: {
    summary: 'ҚЫСҚАША МАЗМҰНЫ',
    keyPoints: 'НЕГІЗГІ ТҰСТАР',
    tasks: 'ТАПСЫРМАЛАР',
    tags: 'ТЕГТЕР',
    transcript: 'ТОЛЫҚ ТРАНСКРИПЦИЯ',
    taskCol: 'Тапсырма',
    priorityCol: 'Маңыздылығы',
    statusCol: 'Мәртебесі',
    pending: 'Күтуде',
    done: 'Орындалды',
    high: 'ЖОҒАРЫ',
    medium: 'ОРТА',
    low: 'ТӨМЕН',
    noTasks: 'Тапсырмалар табылмады.',
    footer: 'Дауыс ботымен жасалған',
  },
};

export function getLabels(lang: string): Labels {
  if (lang === 'ru') return i18n.ru;
  if (lang === 'kk') return i18n.kk;
  return i18n.en;
}
